### ISSUE TITLE
Theme name might be confusing

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/sitenow_standard_lab_theme#1]
Anyone on the standard service will be able to use this theme. Maybe we should remove CLAS from the theme name to avoid confusion.

**Comment by richardbporter** [comment]
Should we change just the display name? Or change it everywhere?

**Comment by bspeare** [comment]
I am fine either way.  Do you want me to change it to uiowa_lab_theme or
just lab_theme?

On Wed, Jan 25, 2017 at 1:55 PM, Richard B. Porter <notifications@github.com

**Comment by genjohnson** [comment]
My preference is to change the machine name to "sitenow_standard_lab_theme", which is consistent with the naming of other themes and modules on the service (we've been trying to reserve the "uiowa" prefix for projects that are not specific to the SiteNow platform), and change the display name to "Lab Theme" since the theme may be used by labs outside of CLAS. 

However, the project should include attribution to the CLAS developers (I'm not sure who all was involved) as the creators and maintainers of this theme in the README.

**Comment by richardbporter** [comment]
I've renamed the repo and will start on replacing it in code.
